Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -33,31 +33,33 @@ jobs:
 
             
   # 🔹 Setup Samsung GCC (glibc2.17-4.8)
-      - name: Setup Samsung Clang
+      
+      - name: Setup Clang r416183b1
         run: |
-                  CLANG_PATH="$PWD/toolchain/clang"
-                  mkdir -p "$CLANG_PATH"
-              
-                  echo "⬇️ Downloading Samsung Clang (r416183b)..."
-                  wget -q https://github.com/sh4dow6oy/samsung_kernel_r5q/releases/download/GCC/clang-r416183b.tar
-              
-                  echo "📦 Extracting Clang..."
-                  tar -xf clang-r416183b.tar -C "$CLANG_PATH"
-              
-                  if [ ! -f "$CLANG_PATH/android-platform-prebuilts-clang-host-linux-x86-32-droidian-clang-r416183b/bin/clang" ]; then
-                    echo "❌ Clang binary not found at $CLANG_PATH/android-platform-prebuilts-clang-host-linux-x86-32-droidian-clang-r416183b/bin/clang"
-                    find "$CLANG_PATH" -type f | head -n20
-                    exit 1
-                  fi
-              
-                  echo "✅ Samsung Clang found at $CLANG_PATH/android-platform-prebuilts-clang-host-linux-x86-32-droidian-clang-r416183b/bin/clang"
-                  echo "PATH=$CLANG_PATH/android-platform-prebuilts-clang-host-linux-x86-32-droidian-clang-r416183b/bin:$PATH" >> $GITHUB_ENV
-                  echo "CC=clang" >> $GITHUB_ENV
-                  echo "LD=ld.lld" >> $GITHUB_ENV
-                  echo "LLVM=1" >> $GITHUB_ENV
-                  echo "LLVM_IAS=1" >> $GITHUB_ENV
-              
-                  $CLANG_PATH/android-platform-prebuilts-clang-host-linux-x86-32-droidian-clang-r416183b/bin/clang --version
+          CLANG_PATH="$PWD/toolchain/clang"
+          mkdir -p "$CLANG_PATH"
+      
+          echo "⬇️ Downloading Clang r416183b1..."
+          wget -q https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/1c1069109f294e9ffbdc1ff8541394ab4b5d941d/clang-r416183b1
+      
+          echo "📦 Extracting Clang..."
+          tar -xf clang-r416183b1.tar.gz -C "$CLANG_PATH"
+      
+          if [ ! -f "$CLANG_PATH/clang-r416183b1/bin/clang" ]; then
+            echo "❌ Clang binary not found at $CLANG_PATH/clang-r416183b1/bin/clang"
+            find "$CLANG_PATH" -type f | head -n20
+            exit 1
+          fi
+      
+          echo "✅ Clang found at $CLANG_PATH/clang-r416183b1/bin/clang"
+          echo "PATH=$CLANG_PATH/clang-r416183b1/bin:$PATH" >> $GITHUB_ENV
+          echo "CC=clang" >> $GITHUB_ENV
+          echo "LD=ld.lld" >> $GITHUB_ENV
+          echo "LLVM=1" >> $GITHUB_ENV
+          echo "LLVM_IAS=1" >> $GITHUB_ENV
+      
+          $CLANG_PATH/clang-r416183b1/bin/clang --version
+
 
 
 
